name: Anthony Profile
favicon: null
layout_spectrum: 0.7546969470568001
typography_spectrum: 0.4573500861879438
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.823349145706743
  lightness: 0.15497801778838038
  saturation: 0.19786739721894264
  rhythmicContrast: 0.273320370586589
purpose: []
