name: Anthony Profile
favicon: null
layout_spectrum: 0.2503
typography_spectrum: 0.4573500861879438
title: Anthony Reyes
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#383838'
    - '#349ed6'
    - '#9c9c9c'
    - '#5f739a'
    - '#35647c'
  brandStrength: 1
  lightness: 0.25
  saturation: 0.8125
  rhythmicContrast: 0.5
purpose: []
